export const entrydata = [
  {
    id: "1",
    name: "EntryTest",
    isDir: true,
    ext: "txt",
    path: "desktop/entry.txt",
  },
  {
    id: "2",
    name: "EntryTest",
    isDir: true,
    ext: "txt",
    path: "desktop/entry.txt",
  },
  // {
  //   id: "3",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "4",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "5",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "6",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "7",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "8",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "9",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
  // {
  //   id: "10",
  //   name: "EntryTest",
  //   isDir: true,
  //   ext: "txt",
  //   path: "desktop/entry.txt",
  // },
];
